### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by fabihoe** [mustafabayar/immo_trakt#8]
Thank you for doing the working and sharing the script with us! It is very unfortunate that they have closed the API. Do you think there is any alternative?

**Comment by mustafabayar** [comment]
Right now I don't know any working free API. If a new API comes out, I will implement it. Feel free to let me know here if you find anything :)

**Comment by fabihoe** [comment]
I was looking for a free API but couldn't find one. I even wrote Immoscout and asked them if the could give one to me in order to compensate for their iOS App that is not properly functioning at the moment. Have you thought of a implementation similar to fredy? (https://github.com/orangecoding/fredy)

**Comment by mustafabayar** [comment]
No, I don't like web scraping. Especially because you need to go around captchas using 3rd party services such as ScrapingAnt or 2Captcha. 
And there are already a couple of flat search projects on Github using scraping. So if I wanted to go with scraping I would use one of those. Either the one you sent or https://github.com/flathunters/flathunter

**Comment by drorata** [comment]
What about paid APIs of immoscout? I'm ready to pay for the data. Any hints or leads?
